name: Build WPR Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Install Android workload
        run: dotnet workload install android

      - name: Verify SDK
        run: |
          dotnet --version
          dotnet --info

      - name: Restore Solution
        run: dotnet restore WPR.sln

      - name: Publish Android APK
        run: |
          dotnet publish \
            UI/WPR.UI.Android/WPR.UI.Android.csproj \
            -c Release \
            -f net6.0-android \
            -r android-arm

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: WPR-APK
          path: |
            **/*.apk
